services:
  mydns-updater:
    build: .
    image: mydns-updater:1.1.x
    container_name: mydns-updater
    restart: unless-stopped
    volumes:
      - ./update.sh:/app/update.sh:ro
      - ./mydns.conf:/app/mydns.conf:ro
      - ./state:/state
    command: ["sh", "/app/update.sh"]
